  name: CI

  on:
    pull_request:
      branches:
        - master

    workflow_dispatch:

  jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: python3 -V
        - name: Build
          run: echo "Build ok"

    test-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: pip install Flask
        - run: python3 app.py 
        - uses: AppThreat/sast-scan-action@master
          with:
            type: "python"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.USERNAME_DOCKER }}
            password: ${{ secrets.PASSWORD_DOCKER }}

        - name: Build Docker image
          run: docker build -t ggtte/reposo:latest .

        - name: Push Docker image
          run: docker push ggtte/reposo:latest
          
        - name: Envio notificação
          if: github.event_name == 'pull_request' || github.event_name == 'push'
          env:
            DISCORD_WEBHOOK: ${{ secrets.WEEBHOOK_DISCORD }}
            run: |
            curl -X POST -H 'Content-type: application/json' \
              --data '{"content":"Nova imagem Docker publicada!"}' \
              $WEBHOOK_DISCORD
              
    ngrok-job:
     runs-on: ubuntu-latest
     needs: build-job
     steps:
       - name: Download and Install ngrok
         run: |
           wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
           unzip ngrok-stable-linux-amd64.zip
           chmod +x ngrok
       - name: Start ngrok
         run: |
          ./ngrok http 8000 &
          sleep 10
          curl -s localhost:4040/api/tunnels | python3 -c "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])" > ngrok-url.txt
       - name: Show ngrok URL
         run: cat ngrok-url.txt
