name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build ok"

 test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@main
        with:
          type: "python"
          
          
          
          
          
